[workspace]
resolver = "2"
members = [
    "dbot-core",
    "storage",
    "bot-runtime",
    "ai-integration",
    "telegram-bot",
    "dbot-cli",
    "openai-client",
    "telegram-bot-examples",
    "telegram-bot-ai",
    "memory",
    "crates/embedding",
    "crates/openai-embedding",
    "crates/bigmodel-embedding",
    "crates/memory-inmemory",
    "crates/memory-sqlite",
    "crates/memory-lance",
    "crates/handler-chain",
    "crates/middleware",
]
