[workspace]
resolver = "2"
members = [
    "dbot-core",
    "storage",
    "ai-handlers",
    "telegram-bot",
    "dbot-cli",
    "openai-client",
    "telegram-bot-examples",
    "telegram-bot-ai",
    "memory",
    "crates/memory/memory-core",
    "crates/memory/memory-strategies",
    "crates/embedding",
    "crates/openai-embedding",
    "crates/bigmodel-embedding",
    "crates/memory/memory-inmemory",
    "crates/memory/memory-sqlite",
    "crates/memory/memory-lance",
    "crates/memory/memory-loader",
    "crates/handler-chain",
    "crates/dbot-telegram",
    "crates/ai-client",
    "crates/middleware",
    "crates/prompt",
]
