[workspace]
resolver = "2"
members = [
    "dbot-core",
    "storage",
    "llm-handlers",
    "telegram-bot",
    "dbot-cli",
    "dbot-llm-cli",
    "crates/llm/openai-client",
    "crates/llm/telegram-bot-llm",
    "memory",
    "crates/memory/memory-core",
    "crates/memory/memory-strategies",
    "crates/embedding/embedding",
    "crates/embedding/openai-embedding",
    "crates/embedding/bigmodel-embedding",
    "crates/memory/memory-inmemory",
    "crates/memory/memory-sqlite",
    "crates/memory/memory-lance",
    "handler-chain",
    "dbot-telegram",
    "crates/llm-client",
    "handlers",
    "crates/prompt",
]
