[workspace]
resolver = "2"
members = [
    "seed-messages",
    "telegram-bot",
    "telegram-llm-bot",
    "telegram-simple-bot",
    "crates/llm/openai-client",
    "crates/llm/telegram-bot-llm",
    "crates/llm-client",
    "crates/memory/memory-lance",
    "crates/prompt",
]
