[workspace]
resolver = "2"
members = [
    "dbot-core",
    "storage",
    "bot-runtime",
    "ai-integration",
    "telegram-bot",
    "dbot-cli",
    "openai-client",
    "telegram-bot-examples",
    "telegram-bot-ai",
    "memory",
]
