[package]
name = "image-handlers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
dbot-core = { path = "../dbot-core" }
image-generation-client = { path = "../crates/image-generation-client" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
anyhow = "1.0"
