[package]
name = "memory-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = "0.4"
telegram-bot = { path = "../../../telegram-bot" }
embedding = { path = "../../embedding/embedding" }
tracing = "0.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
telegram-bot = { path = "../../../telegram-bot" }
tokio = { version = "1", features = ["full"] }
